name: Carbon SendGrid Adapter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - latest
        experimental:
          - false
        include:
          - crystal_version: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.4.0
          - latest
        experimental:
          - false
        include:
          - crystal_version: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec
